# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd50024901ddebfc27f62fe5d8cc89182a4470435265202a18f9fbc7c5cf928160c2e2ff57450b5921ede592e62511d5cc21b663f2b2fe0a4c816de8625586d1

test:
  secret_key_base: b81a68d78fc0beb666a264a6d0c6359827607384454cbef1ea53c05f6040f6e168ba50bbfa99d15c78233683d713af5dcb2536ea70d942d7435a2e760fc974e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
